CONTIKI_PROJECT = decreased-rank-attacker decreased-rank-blackhole decreased-rank-attacker-const
all: $(CONTIKI_PROJECT)

CONTIKI=../../..
MODULES_REL += ./attacking-rpl

include $(CONTIKI)/Makefile.include
