#define ENERGEST_CONF_ON 1
// #define NETSTACK_CONF_FRAMER  framer_802154
// #define UIP_CONF_DS6_ADDR_NBU 1
// #define UIP_CONF_DS6_DEFRT_NBU 1
// #define UIP_CONF_DS6_PREFIX_NBU 1

#define LOG_CONF_LEVEL_MAC LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAIN LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_INFO
