CONTIKI_PROJECT = dis-flooder dag-version-dio non-rpl-blackhole-node dao-blackhole-node
all: $(CONTIKI_PROJECT)

CONTIKI=../../..
MODULES_REL += custom-lib/rpl-lite

include $(CONTIKI)/Makefile.include
